version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directiry: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
