version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.10.0-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
